server:
  port: 19000
logging:
  file: ./log/data-pipeline.log
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} -%5level [data-synchronize][%15.15thread] %-40.40logger{39} [%6line]: %msg%n"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data-synchronize?useSSL=false
    password: xxx
    username: xxx
    tomcat:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

data-pipeline-properties:
  bootstrap-servers: 172.28.2.22:9090,172.28.2.22:9091,172.28.2.22:9092
  group-id: data-pipeline-dt
  consumer-count: 20000
  elasticsearch-hostname: 172.28.10.67
  elasticsearch-port: 9200
  elasticsearch-scheme: http
  slack-url: xxx
  message-event-topic: xxx
  date-synchronize-error-topic: xxx
  product-date-refresh-topic: xxx
  event-tracking-bootstrap-servers: xxx
  event-tracking-group-id: xxx
  event-tracking-consumer-count: xxx
  event-tracking-elasticsearch-hostname: xxx
  event-tracking-elasticsearch-port: xxx
  event-tracking-elasticsearch-scheme: xxx
