version: '3'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.1.3'
    volumes:
      - /home/ubuntu/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/ubuntu/elasticsearch/config/synonyms:/usr/share/elasticsearch/config/synonyms
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx4096m -Xms4096m"
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.1.3'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch