package codexe.han.elasticsearch.test;

import lombok.extern.slf4j.Slf4j;
import org.apache.http.HttpHost;
import org.elasticsearch.action.bulk.BulkRequest;
import org.elasticsearch.action.bulk.BulkResponse;
import org.elasticsearch.action.search.*;
import org.elasticsearch.action.update.UpdateRequest;
import org.elasticsearch.client.RequestOptions;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.index.query.BoolQueryBuilder;
import org.elasticsearch.index.query.QueryBuilders;
import org.elasticsearch.search.Scroll;
import org.elasticsearch.search.SearchHit;
import org.elasticsearch.search.builder.SearchSourceBuilder;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Slf4j
public class InitGarmentNames {
    public static void main(String[] args) {
        Map<Integer, String> garmentTable = getGarmentTable();

        String ip = "172.28.10.67";
        String schema = "http";
        Integer port = 9200;

        RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost(ip, port, schema)));
        final Scroll scroll = new Scroll(TimeValue.timeValueMinutes(1L));
        SearchRequest searchRequest = new SearchRequest("deja_street_for_analysis");
        searchRequest.types("tags");
        searchRequest.scroll(scroll);
        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
        searchSourceBuilder.size(5000);
        BoolQueryBuilder boolQuery = QueryBuilders.boolQuery();
        boolQuery.must(QueryBuilders.termQuery("is_recommended", true));
        boolQuery.must(QueryBuilders.termQuery("is_delete", false));
        searchSourceBuilder.query(boolQuery);
        searchRequest.source(searchSourceBuilder);

        int page = 1;
        try{
            SearchResponse searchResponse = client.search(searchRequest, RequestOptions.DEFAULT);
            String scrollId = searchResponse.getScrollId();
            SearchHit[] searchHits = searchResponse.getHits().getHits();

            while (searchHits != null && searchHits.length > 0) {
                BulkRequest bulkRequest = new BulkRequest();

                for (SearchHit hit : searchHits) {
                    Map<String, Object> sourceMap = hit.getSourceAsMap();
                    if(sourceMap.keySet().contains("garment1_name")){
                        sourceMap.put("garment1_name","");
                    }
                    if(sourceMap.keySet().contains("garment2_name")){
                        sourceMap.put("garment2_name","");
                    }
                    if(sourceMap.keySet().contains("garment3_name")){
                        sourceMap.put("garment3_name","");
                    }
                    if(sourceMap.keySet().contains("garment4_name")){
                        sourceMap.put("garment4_name","");
                    }
                    if(sourceMap.keySet().contains("garment5_name")){
                        sourceMap.put("garment5_name","");
                    }

                    if(sourceMap.keySet().contains("garments")){
                        List<Long> garmentIds = (List<Long>) sourceMap.get("garments");
                        for(int i=0; i<garmentIds.size(); i++){
                            String garmentName = "";
                            if(i==0) garmentName = "garment1_name";
                            if(i==1) garmentName = "garment2_name";
                            if(i==2) garmentName = "garment3_name";
                            if(i==3) garmentName = "garment4_name";
                            if(i==4) garmentName = "garment5_name";
                            sourceMap.put(garmentName, garmentTable.get(garmentIds.get(i)));
                        }
                        UpdateRequest updateRequest = new UpdateRequest("deja_street_for_analysis", "tags", hit.getId());
                        updateRequest.doc(sourceMap);
                        bulkRequest.add(updateRequest);
                    }

                }

                //bulk update
                if(bulkRequest.numberOfActions()!=0) {
                    BulkResponse bulkResponse = client.bulk(bulkRequest, RequestOptions.DEFAULT);
                    if (bulkResponse.hasFailures()) {
                        log.error("failure reason is {}", bulkResponse.buildFailureMessage());
                    } else {
                        log.info("no failures");
                    }
                }
                log.info("update page {} done", page++);
                SearchScrollRequest scrollRequest = new SearchScrollRequest(scrollId);
                scrollRequest.scroll(scroll);
                searchResponse = client.scroll(scrollRequest, RequestOptions.DEFAULT);
                scrollId = searchResponse.getScrollId();
                searchHits = searchResponse.getHits().getHits();
            }

            ClearScrollRequest clearScrollRequest = new ClearScrollRequest();
            clearScrollRequest.addScrollId(scrollId);
            ClearScrollResponse clearScrollResponse = client.clearScroll(clearScrollRequest, RequestOptions.DEFAULT);
            boolean succeeded = clearScrollResponse.isSucceeded();
            log.info("clear scroll response {}", succeeded);
            client.close();
        }catch(Exception e){
            log.error("update es error", e);
        }
    }

    public static Map<Integer, String> getGarmentTable(){
        Map<Integer, String> garmentNameMap = new HashMap<>();
        garmentNameMap.put(1, "ed Blouse & Shirt");
        garmentNameMap.put(2, "ed T-Shirt");
        garmentNameMap.put(3, "ed Tunic");
        garmentNameMap.put(4, "ed Cropped Top");
        garmentNameMap.put(5, "ed Straight Skirt");
        garmentNameMap.put(6, "ed A-Line Skirt");
        garmentNameMap.put(7, "ed Jacket");
        garmentNameMap.put(8, "ed Coat");
        garmentNameMap.put(9, "ed Blazer");
        garmentNameMap.put(10,"red Short");
        garmentNameMap.put(11,"red Bodycon & Sheath Dress");
        garmentNameMap.put(12,"red A-line Dress");
        garmentNameMap.put(13,"red Tank Top");
        garmentNameMap.put(14,"red Bodycon Skirt");
        garmentNameMap.put(15,"red Vest");
        garmentNameMap.put(16,"red Sweater");
        garmentNameMap.put(17,"red Cardigan");
        garmentNameMap.put(18,"red Joggers & Legging");
        garmentNameMap.put(19,"red Pant");
        garmentNameMap.put(20,"red Jean");
        garmentNameMap.put(21,"red Playsuit");
        garmentNameMap.put(22,"red Jumpsuit");
        garmentNameMap.put(23,"red Shift & Shirt Dress");
        garmentNameMap.put(24,"red Bodysuit");
        garmentNameMap.put(25,"pink Blouse & Shirt");
        garmentNameMap.put(26,"pink T-Shirt");
        garmentNameMap.put(27,"pink Tunic");
        garmentNameMap.put(28,"pink Cropped Top");
        garmentNameMap.put(29,"pink Straight Skirt");
        garmentNameMap.put(30,"pink A-Line Skirt");
        garmentNameMap.put(31,"pink Jacket");
        garmentNameMap.put(32,"pink Coat");
        garmentNameMap.put(33,"pink Blazer");
        garmentNameMap.put(34,"pink Short");
        garmentNameMap.put(35,"pink Bodycon & Sheath Dress");
        garmentNameMap.put(36,"pink A-line Dress");
        garmentNameMap.put(37,"pink Tank Top");
        garmentNameMap.put(38,"pink Bodycon Skirt");
        garmentNameMap.put(39,"pink Vest");
        garmentNameMap.put(40,"pink Sweater");
        garmentNameMap.put(41,"pink Cardigan");
        garmentNameMap.put(42,"pink Joggers & Legging");
        garmentNameMap.put(43,"pink Pant");
        garmentNameMap.put(44,"pink Jean");
        garmentNameMap.put(45,"pink Playsuit");
        garmentNameMap.put(46,"pink Jumpsuit");
        garmentNameMap.put(47,"pink Shift & Shirt Dress");
        garmentNameMap.put(48,"pink Bodysuit");
        garmentNameMap.put(49,"nude Blouse & Shirt");
        garmentNameMap.put(50,"nude T-Shirt");
        garmentNameMap.put(51,"nude Tunic");
        garmentNameMap.put(52,"nude Cropped Top");
        garmentNameMap.put(53,"nude Straight Skirt");
        garmentNameMap.put(54,"nude A-Line Skirt");
        garmentNameMap.put(55,"nude Jacket");
        garmentNameMap.put(56,"nude Coat");
        garmentNameMap.put(57,"nude Blazer");
        garmentNameMap.put(58,"nude Short");
        garmentNameMap.put(59,"nude Bodycon & Sheath Dress");
        garmentNameMap.put(60,"nude A-line Dress");
        garmentNameMap.put(61,"nude Tank Top");
        garmentNameMap.put(62,"nude Bodycon Skirt");
        garmentNameMap.put(63,"nude Vest");
        garmentNameMap.put(64,"nude Sweater");
        garmentNameMap.put(65,"nude Cardigan");
        garmentNameMap.put(66,"nude Joggers & Legging");
        garmentNameMap.put(67,"nude Pant");
        garmentNameMap.put(68,"nude Jean");
        garmentNameMap.put(69,"nude Playsuit");
        garmentNameMap.put(70,"nude Jumpsuit");
        garmentNameMap.put(71,"nude Shift & Shirt Dress");
        garmentNameMap.put(72,"nude Bodysuit");
        garmentNameMap.put(73,"orange Blouse & Shirt");
        garmentNameMap.put(74,"orange T-Shirt");
        garmentNameMap.put(75,"orange Tunic");
        garmentNameMap.put(76,"orange Cropped Top");
        garmentNameMap.put(77,"orange Straight Skirt");
        garmentNameMap.put(78,"orange A-Line Skirt");
        garmentNameMap.put(79,"orange Jacket");
        garmentNameMap.put(80,"orange Coat");
        garmentNameMap.put(81,"orange Blazer");
        garmentNameMap.put(82,"orange Short");
        garmentNameMap.put(83,"orange Bodycon & Sheath Dress");
        garmentNameMap.put(84,"orange A-line Dress");
        garmentNameMap.put(85,"orange Tank Top");
        garmentNameMap.put(86,"orange Bodycon Skirt");
        garmentNameMap.put(87,"orange Vest");
        garmentNameMap.put(88,"orange Sweater");
        garmentNameMap.put(89,"orange Cardigan");
        garmentNameMap.put(90,"orange Joggers & Legging");
        garmentNameMap.put(91,"orange Pant");
        garmentNameMap.put(92,"orange Jean");
        garmentNameMap.put(93,"orange Playsuit");
        garmentNameMap.put(94,"orange Jumpsuit");
        garmentNameMap.put(95,"orange Shift & Shirt Dress");
        garmentNameMap.put(96,"orange Bodysuit");
        garmentNameMap.put(97,"yellow Blouse & Shirt");
        garmentNameMap.put(98,"yellow T-Shirt");
        garmentNameMap.put(99,"yellow Tunic");
        garmentNameMap.put(100,"yellow Cropped Top");
        garmentNameMap.put(101,"yellow Straight Skirt");
        garmentNameMap.put(102,"yellow A-Line Skirt");
        garmentNameMap.put(103,"yellow Jacket");
        garmentNameMap.put(104,"yellow Coat");
        garmentNameMap.put(105,"yellow Blazer");
        garmentNameMap.put(106,"yellow Short");
        garmentNameMap.put(107,"yellow Bodycon & Sheath Dress");
        garmentNameMap.put(108,"yellow A-line Dress");
        garmentNameMap.put(109,"yellow Tank Top");
        garmentNameMap.put(110,"yellow Bodycon Skirt");
        garmentNameMap.put(111,"yellow Vest");
        garmentNameMap.put(112,"yellow Sweater");
        garmentNameMap.put(113,"yellow Cardigan");
        garmentNameMap.put(114,"yellow Joggers & Legging");
        garmentNameMap.put(115,"yellow Pant");
        garmentNameMap.put(116,"yellow Jean");
        garmentNameMap.put(117,"yellow Playsuit");
        garmentNameMap.put(118,"yellow Jumpsuit");
        garmentNameMap.put(119,"yellow Shift & Shirt Dress");
        garmentNameMap.put(120,"yellow Bodysuit");
        garmentNameMap.put(121,"blue Blouse & Shirt");
        garmentNameMap.put(122,"blue T-Shirt");
        garmentNameMap.put(123,"blue Tunic");
        garmentNameMap.put(124,"blue Cropped Top");
        garmentNameMap.put(125,"blue Straight Skirt");
        garmentNameMap.put(126,"blue A-Line Skirt");
        garmentNameMap.put(127,"blue Jacket");
        garmentNameMap.put(128,"blue Coat");
        garmentNameMap.put(129,"blue Blazer");
        garmentNameMap.put(130,"blue Short");
        garmentNameMap.put(131,"blue Bodycon & Sheath Dress");
        garmentNameMap.put(132,"blue A-line Dress");
        garmentNameMap.put(133,"blue Tank Top");
        garmentNameMap.put(134,"blue Bodycon Skirt");
        garmentNameMap.put(135,"blue Vest");
        garmentNameMap.put(136,"blue Sweater");
        garmentNameMap.put(137,"blue Cardigan");
        garmentNameMap.put(138,"blue Joggers & Legging");
        garmentNameMap.put(139,"blue Pant");
        garmentNameMap.put(140,"blue Jean");
        garmentNameMap.put(141,"blue Playsuit");
        garmentNameMap.put(142,"blue Jumpsuit");
        garmentNameMap.put(143,"blue Shift & Shirt Dress");
        garmentNameMap.put(144,"blue Bodysuit");
        garmentNameMap.put(145,"purple Blouse & Shirt");
        garmentNameMap.put(146,"purple T-Shirt");
        garmentNameMap.put(147,"purple Tunic");
        garmentNameMap.put(148,"purple Cropped Top");
        garmentNameMap.put(149,"purple Straight Skirt");
        garmentNameMap.put(150,"purple A-Line Skirt");
        garmentNameMap.put(151,"purple Jacket");
        garmentNameMap.put(152,"purple Coat");
        garmentNameMap.put(153,"purple Blazer");
        garmentNameMap.put(154,"purple Short");
        garmentNameMap.put(155,"purple Bodycon & Sheath Dress");
        garmentNameMap.put(156,"purple A-line Dress");
        garmentNameMap.put(157,"purple Tank Top");
        garmentNameMap.put(158,"purple Bodycon Skirt");
        garmentNameMap.put(159,"purple Vest");
        garmentNameMap.put(160,"purple Sweater");
        garmentNameMap.put(161,"purple Cardigan");
        garmentNameMap.put(162,"purple Joggers & Legging");
        garmentNameMap.put(163,"purple Pant");
        garmentNameMap.put(164,"purple Jean");
        garmentNameMap.put(165,"purple Playsuit");
        garmentNameMap.put(166,"purple Jumpsuit");
        garmentNameMap.put(167,"purple Shift & Shirt Dress");
        garmentNameMap.put(168,"purple Bodysuit");
        garmentNameMap.put(169,"brown Blouse & Shirt");
        garmentNameMap.put(170,"brown T-Shirt");
        garmentNameMap.put(171,"brown Tunic");
        garmentNameMap.put(172,"brown Cropped Top");
        garmentNameMap.put(173,"brown Straight Skirt");
        garmentNameMap.put(174,"brown A-Line Skirt");
        garmentNameMap.put(175,"brown Jacket");
        garmentNameMap.put(176,"brown Coat");
        garmentNameMap.put(177,"brown Blazer");
        garmentNameMap.put(178,"brown Short");
        garmentNameMap.put(179,"brown Bodycon & Sheath Dress");
        garmentNameMap.put(180,"brown A-line Dress");
        garmentNameMap.put(181,"brown Tank Top");
        garmentNameMap.put(182,"brown Bodycon Skirt");
        garmentNameMap.put(183,"brown Vest");
        garmentNameMap.put(184,"brown Sweater");
        garmentNameMap.put(185,"brown Cardigan");
        garmentNameMap.put(186,"brown Joggers & Legging");
        garmentNameMap.put(187,"brown Pant");
        garmentNameMap.put(188,"brown Jean");
        garmentNameMap.put(189,"brown Playsuit");
        garmentNameMap.put(190,"brown Jumpsuit");
        garmentNameMap.put(191,"brown Shift & Shirt Dress");
        garmentNameMap.put(192,"brown Bodysuit");
        garmentNameMap.put(193,"grey Blouse & Shirt");
        garmentNameMap.put(194,"grey T-Shirt");
        garmentNameMap.put(195,"grey Tunic");
        garmentNameMap.put(196,"grey Cropped Top");
        garmentNameMap.put(197,"grey Straight Skirt");
        garmentNameMap.put(198,"grey A-Line Skirt");
        garmentNameMap.put(199,"grey Jacket");
        garmentNameMap.put(200,"grey Coat");
        garmentNameMap.put(201,"grey Blazer");
        garmentNameMap.put(202,"grey Short");
        garmentNameMap.put(203,"grey Bodycon & Sheath Dress");
        garmentNameMap.put(204,"grey A-line Dress");
        garmentNameMap.put(205,"grey Tank Top");
        garmentNameMap.put(206,"grey Bodycon Skirt");
        garmentNameMap.put(207,"grey Vest");
        garmentNameMap.put(208,"grey Sweater");
        garmentNameMap.put(209,"grey Cardigan");
        garmentNameMap.put(210,"grey Joggers & Legging");
        garmentNameMap.put(211,"grey Pant");
        garmentNameMap.put(212,"grey Jean");
        garmentNameMap.put(213,"grey Playsuit");
        garmentNameMap.put(214,"grey Jumpsuit");
        garmentNameMap.put(215,"grey Shift & Shirt Dress");
        garmentNameMap.put(216,"grey Bodysuit");
        garmentNameMap.put(217,"black Blouse & Shirt");
        garmentNameMap.put(218,"black T-Shirt");
        garmentNameMap.put(219,"black Tunic");
        garmentNameMap.put(220,"black Cropped Top");
        garmentNameMap.put(221,"black Straight Skirt");
        garmentNameMap.put(222,"black A-Line Skirt");
        garmentNameMap.put(223,"black Jacket");
        garmentNameMap.put(224,"black Coat");
        garmentNameMap.put(225,"black Blazer");
        garmentNameMap.put(226,"black Short");
        garmentNameMap.put(227,"black Bodycon & Sheath Dress");
        garmentNameMap.put(228,"black A-line Dress");
        garmentNameMap.put(229,"black Tank Top");
        garmentNameMap.put(230,"black Bodycon Skirt");
        garmentNameMap.put(231,"black Vest");
        garmentNameMap.put(232,"black Sweater");
        garmentNameMap.put(233,"black Cardigan");
        garmentNameMap.put(234,"black Joggers & Legging");
        garmentNameMap.put(235,"black Pant");
        garmentNameMap.put(236,"black Jean");
        garmentNameMap.put(237,"black Playsuit");
        garmentNameMap.put(238,"black Jumpsuit");
        garmentNameMap.put(239,"black Shift & Shirt Dress");
        garmentNameMap.put(240,"black Bodysuit");
        garmentNameMap.put(241,"white & cream Blouse & Shirt");
        garmentNameMap.put(242,"white & cream T-Shirt");
        garmentNameMap.put(243,"white & cream Tunic");
        garmentNameMap.put(244,"white & cream Cropped Top");
        garmentNameMap.put(245,"white & cream Straight Skirt");
        garmentNameMap.put(246,"white & cream A-Line Skirt");
        garmentNameMap.put(247,"white & cream Jacket");
        garmentNameMap.put(248,"white & cream Coat");
        garmentNameMap.put(249,"white & cream Blazer");
        garmentNameMap.put(250,"white & cream Short");
        garmentNameMap.put(251,"white & cream Bodycon & Sheath Dress");
        garmentNameMap.put(252,"white & cream A-line Dress");
        garmentNameMap.put(253,"white & cream Tank Top");
        garmentNameMap.put(254,"white & cream Bodycon Skirt");
        garmentNameMap.put(255,"white & cream Vest");
        garmentNameMap.put(256,"white & cream Sweater");
        garmentNameMap.put(257,"white & cream Cardigan");
        garmentNameMap.put(258,"white & cream Joggers & Legging");
        garmentNameMap.put(259,"white & cream Pant");
        garmentNameMap.put(260,"white & cream Jean");
        garmentNameMap.put(261,"white & cream Playsuit");
        garmentNameMap.put(262,"white & cream Jumpsuit");
        garmentNameMap.put(263,"white & cream Shift & Shirt Dress");
        garmentNameMap.put(264,"white & cream Bodysuit");
        garmentNameMap.put(265,"floral Blouse & Shirt");
        garmentNameMap.put(266,"floral T-Shirt");
        garmentNameMap.put(267,"floral Tunic");
        garmentNameMap.put(268,"floral Cropped Top");
        garmentNameMap.put(269,"floral Straight Skirt");
        garmentNameMap.put(270,"floral A-Line Skirt");
        garmentNameMap.put(271,"floral Jacket");
        garmentNameMap.put(272,"floral Coat");
        garmentNameMap.put(273,"floral Blazer");
        garmentNameMap.put(274,"floral Short");
        garmentNameMap.put(275,"floral Bodycon & Sheath Dress");
        garmentNameMap.put(276,"floral A-line Dress");
        garmentNameMap.put(277,"floral Tank Top");
        garmentNameMap.put(278,"floral Bodycon Skirt");
        garmentNameMap.put(279,"floral Vest");
        garmentNameMap.put(280,"floral Sweater");
        garmentNameMap.put(281,"floral Cardigan");
        garmentNameMap.put(282,"floral Joggers & Legging");
        garmentNameMap.put(283,"floral Pant");
        garmentNameMap.put(284,"floral Jean");
        garmentNameMap.put(285,"floral Playsuit");
        garmentNameMap.put(286,"floral Jumpsuit");
        garmentNameMap.put(287,"floral Shift & Shirt Dress");
        garmentNameMap.put(288,"floral Bodysuit");
        garmentNameMap.put(289,"stripes Blouse & Shirt");
        garmentNameMap.put(290,"stripes T-Shirt");
        garmentNameMap.put(291,"stripes Tunic");
        garmentNameMap.put(292,"stripes Cropped Top");
        garmentNameMap.put(293,"stripes Straight Skirt");
        garmentNameMap.put(294,"stripes A-Line Skirt");
        garmentNameMap.put(295,"stripes Jacket");
        garmentNameMap.put(296,"stripes Coat");
        garmentNameMap.put(297,"stripes Blazer");
        garmentNameMap.put(298,"stripes Short");
        garmentNameMap.put(299,"stripes Bodycon & Sheath Dress");
        garmentNameMap.put(300,"stripes A-line Dress");
        garmentNameMap.put(301,"stripes Tank Top");
        garmentNameMap.put(302,"stripes Bodycon Skirt");
        garmentNameMap.put(303,"stripes Vest");
        garmentNameMap.put(304,"stripes Sweater");
        garmentNameMap.put(305,"stripes Cardigan");
        garmentNameMap.put(306,"stripes Joggers & Legging");
        garmentNameMap.put(307,"stripes Pant");
        garmentNameMap.put(308,"stripes Jean");
        garmentNameMap.put(309,"stripes Playsuit");
        garmentNameMap.put(310,"stripes Jumpsuit");
        garmentNameMap.put(311,"stripes Shift & Shirt Dress");
        garmentNameMap.put(312,"stripes Bodysuit");
        garmentNameMap.put(313,"dots Blouse & Shirt");
        garmentNameMap.put(314,"dots T-Shirt");
        garmentNameMap.put(315,"dots Tunic");
        garmentNameMap.put(316,"dots Cropped Top");
        garmentNameMap.put(317,"dots Straight Skirt");
        garmentNameMap.put(318,"dots A-Line Skirt");
        garmentNameMap.put(319,"dots Jacket");
        garmentNameMap.put(320,"dots Coat");
        garmentNameMap.put(321,"dots Blazer");
        garmentNameMap.put(322,"dots Short");
        garmentNameMap.put(323,"dots Bodycon & Sheath Dress");
        garmentNameMap.put(324,"dots A-line Dress");
        garmentNameMap.put(325,"dots Tank Top");
        garmentNameMap.put(326,"dots Bodycon Skirt");
        garmentNameMap.put(327,"dots Vest");
        garmentNameMap.put(328,"dots Sweater");
        garmentNameMap.put(329,"dots Cardigan");
        garmentNameMap.put(330,"dots Joggers & Legging");
        garmentNameMap.put(331,"dots Pant");
        garmentNameMap.put(332,"dots Jean");
        garmentNameMap.put(333,"dots Playsuit");
        garmentNameMap.put(334,"dots Jumpsuit");
        garmentNameMap.put(335,"dots Shift & Shirt Dress");
        garmentNameMap.put(336,"dots Bodysuit");
        garmentNameMap.put(337,"checks Blouse & Shirt");
        garmentNameMap.put(338,"checks T-Shirt");
        garmentNameMap.put(339,"checks Tunic");
        garmentNameMap.put(340,"checks Cropped Top");
        garmentNameMap.put(341,"checks Straight Skirt");
        garmentNameMap.put(342,"checks A-Line Skirt");
        garmentNameMap.put(343,"checks Jacket");
        garmentNameMap.put(344,"checks Coat");
        garmentNameMap.put(345,"checks Blazer");
        garmentNameMap.put(346,"checks Short");
        garmentNameMap.put(347,"checks Bodycon & Sheath Dress");
        garmentNameMap.put(348,"checks A-line Dress");
        garmentNameMap.put(349,"checks Tank Top");
        garmentNameMap.put(350,"checks Bodycon Skirt");
        garmentNameMap.put(351,"checks Vest");
        garmentNameMap.put(352,"checks Sweater");
        garmentNameMap.put(353,"checks Cardigan");
        garmentNameMap.put(354,"checks Joggers & Legging");
        garmentNameMap.put(355,"checks Pant");
        garmentNameMap.put(356,"checks Jean");
        garmentNameMap.put(357,"checks Playsuit");
        garmentNameMap.put(358,"checks Jumpsuit");
        garmentNameMap.put(359,"checks Shift & Shirt Dress");
        garmentNameMap.put(360,"checks Bodysuit");
        garmentNameMap.put(361,"color-blocking Blouse & Shirt");
        garmentNameMap.put(362,"color-blocking T-Shirt");
        garmentNameMap.put(363,"color-blocking Tunic");
        garmentNameMap.put(364,"color-blocking Cropped Top");
        garmentNameMap.put(365,"color-blocking Straight Skirt");
        garmentNameMap.put(366,"color-blocking A-Line Skirt");
        garmentNameMap.put(367,"color-blocking Jacket");
        garmentNameMap.put(368,"color-blocking Coat");
        garmentNameMap.put(369,"color-blocking Blazer");
        garmentNameMap.put(370,"color-blocking Short");
        garmentNameMap.put(371,"color-blocking Bodycon & Sheath Dress");
        garmentNameMap.put(372,"color-blocking A-line Dress");
        garmentNameMap.put(373,"color-blocking Tank Top");
        garmentNameMap.put(374,"color-blocking Bodycon Skirt");
        garmentNameMap.put(375,"color-blocking Vest");
        garmentNameMap.put(376,"color-blocking Sweater");
        garmentNameMap.put(377,"color-blocking Cardigan");
        garmentNameMap.put(378,"color-blocking Joggers & Legging");
        garmentNameMap.put(379,"color-blocking Pant");
        garmentNameMap.put(380,"color-blocking Jean");
        garmentNameMap.put(381,"color-blocking Playsuit");
        garmentNameMap.put(382,"color-blocking Jumpsuit");
        garmentNameMap.put(383,"color-blocking Shift & Shirt Dress");
        garmentNameMap.put(384,"color-blocking Bodysuit");
        garmentNameMap.put(385,"animal print Blouse & Shirt");
        garmentNameMap.put(386,"animal print T-Shirt");
        garmentNameMap.put(387,"animal print Tunic");
        garmentNameMap.put(388,"animal print Cropped Top");
        garmentNameMap.put(389,"animal print Straight Skirt");
        garmentNameMap.put(390,"animal print A-Line Skirt");
        garmentNameMap.put(391,"animal print Jacket");
        garmentNameMap.put(392,"animal print Coat");
        garmentNameMap.put(393,"animal print Blazer");
        garmentNameMap.put(394,"animal print Short");
        garmentNameMap.put(395,"animal print Bodycon & Sheath Dress");
        garmentNameMap.put(396,"animal print A-line Dress");
        garmentNameMap.put(397,"animal print Tank Top");
        garmentNameMap.put(398,"animal print Bodycon Skirt");
        garmentNameMap.put(399,"animal print Vest");
        garmentNameMap.put(400,"animal print Sweater");
        garmentNameMap.put(401,"animal print Cardigan");
        garmentNameMap.put(402,"animal print Joggers & Legging");
        garmentNameMap.put(403,"animal print Pant");
        garmentNameMap.put(404,"animal print Jean");
        garmentNameMap.put(405,"animal print Playsuit");
        garmentNameMap.put(406,"animal print Jumpsuit");
        garmentNameMap.put(407,"animal print Shift & Shirt Dress");
        garmentNameMap.put(408,"animal print Bodysuit");

        return garmentNameMap;
    }
}
